# Отображение информации согласно выставленного уровня логирования
# DEBUG - Максимальное отображение всех сообщений.
# INFO - Отображение всех сообщений кроме отладочных (DEBUG)
# UPDATE - Выводит информацию об обновлении Базы данных или в файле runtime-lavamoat.js (пользовательский уровень).
# WARNING - Отображение всех сообщений кроме отладочных и информационных (DEBUG, INFO)
# ERROR - Отображение всех сообщений кроме отладочных, информационных и предупреждающих (DEBUG, INFO, WARNING)
LOG_LEVEL: DEBUG  # DEBUG, INFO, WARNING, ERROR

# Глобальные настройки скрипта
GLOBAL_SETTINGS:
  # Режим работы скрипта автоматический или интерактивный.
  AUTO_MODE: false  # Если true, то автоматический режим, false - интерактивный режим
    # Если в файле config.yaml выставлен режим работы в AUTO_MODE: true, то выполните один раз это действие для перехода в автоматический запуск скрипта.
    # 1) Запустите PowerShell от имени администратора
    # 2) Перейдите в директорию проекта: (для примера) cd D:\Python\Automation-MetaMask-MoreLogin
    # 3) Активируйте виртуальное окружение: .\.venv\Scripts\Activate
    # 4) Запустите скрипт: python main.py (для windows) или python3 main.py (для linux)
  MIN_INTERVAL_MINUTES: 10 # Минимальный интервал между запусками (в минутах). Для работы в режиме AUTO_MODE: true.
  MAX_INTERVAL_MINUTES: 30 # Максимальный интервал между запусками (в минутах). Для работы в режиме AUTO_MODE: true.

  # Если AUTO_MODE: false, то тогда запустите интерактивный режим, вводя дополнительные команды в консоли.
  # Интерактивный режим. (выбор опций в консоли в процессе работы скрипта).
  MODE_CLOSE_PROFILE: true  # Закрывать профиль после выполнения: TRUE/FALSE.
  # Перемешивать профили при обработке нескольких: TRUE/FALSE.
  MIX_PROFILES: true
  # Задержка между профилями
  PROFILE_DELAY:
    ENABLED: false  # true - задержка включена по умолчанию, false - выключена
    MIN: 10       # null - задержка отключена, число - минимальное время в секундах
    MAX: 120       # null - задержка отключена, число - максимальное время в секундах




# Настройки обработки активностей MonadFaucet
ACTIVITY_SETTINGS:
  # Автоматически выполнять активность при неожиданном статусе: TRUE/FALSE
  AUTO_PROCESS_UNEXPECTED_STATUS: true
  # Время ожидания после успешной активности (часы, минуты)
  SUCCESS_WAIT_TIME:
    HOURS: 24
    MINUTES: 3
  # Максимальное количество хранимых записей для каждого профиля в БД: crypto_activities
  MAX_RECORDS_PER_PROFILE: 5

# Настройки обработки активностей Kuru
KURU_ACTIVITY_SETTINGS:
  # Количество свапов для каждого профиля за сессию
  MIN_SWAPS: 1
  MAX_SWAPS: 6

  # Для свапа MON на другие токены
  MIN_PERCENT_MON: 5 # минимальный процент от свапа MON
  MAX_PERCENT_MON: 20 # максимальный процент от свапа MON

  # Для свапа других токенов на MON
  MIN_PERCENT_TOKEN: 95 # минимальный процент от свапа других токенов
  MAX_PERCENT_TOKEN: 98 # максимальный процент от свапа других токенов

  # Время ожидания после успешной свапа (часы, минуты)
  MIN_WAIT_TIME_BETWEEN_SWAP: 5 # минимальное время ожидания после успешного свапа
  MAX_WAIT_TIME_BETWEEN_SWAP: 15 # максимальное время ожидания после успешного свапа

