# Отображение информации согласно выставленного уровня логирования
# DEBUG - Максимальное отображение всех сообщений.
# INFO - Отображение всех сообщений кроме отладочных (DEBUG)
# UPDATE - Выводит информацию об обновлении Базы данных или в файле runtime-lavamoat.js (пользовательский уровень).
# WARNING - Отображение всех сообщений кроме отладочных и информационных (DEBUG, INFO)
# ERROR - Отображение всех сообщений кроме отладочных, информационных и предупреждающих (DEBUG, INFO, WARNING)
LOG_LEVEL: DEBUG  # DEBUG, INFO, WARNING, ERROR

