

# Берется из MoreLogin, Центр настоек -> Локальные настройки (D:\.MoreLogin\cache)
# По умолчанию в этой папке хранится кэш временных файлов.
path_local_cashe: D:\.MoreLogin\cache

# Берется из MoreLogin, Профиль Браузера -> API
BASEURL: http://127.0.0.1:40000

# Отображение информации согласно выставленного уровня логирования
# DEBUG - Максимальное отображение всех сообщений.
# INFO - Отображение всех сообщений кроме отладочных (DEBUG)
# WARNING - Отображение всех сообщений кроме отладочных и информационных (DEBUG, INFO)
# ERROR - Отображение всех сообщений кроме отладочных, информационных и предупреждающих (DEBUG, INFO, WARNING)
LOG_LEVEL: DEBUG  # DEBUG, INFO, WARNING, ERROR
